-- ============================================================
-- BioBridge Provider: Staff & Permissions System
-- Run in Supabase SQL Editor
-- ============================================================

-- 1. PROVIDER USERS TABLE
CREATE TABLE IF NOT EXISTS public.provider_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  pin VARCHAR(100) NOT NULL,
  full_name VARCHAR(150),
  email VARCHAR(200),
  role VARCHAR(30) NOT NULL DEFAULT 'PROVIDER_MONITOR' 
    CHECK (role IN ('PROVIDER_OWNER','PROVIDER_ADMIN','PROVIDER_BILLING','PROVIDER_SUPPORT','PROVIDER_MONITOR')),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. PROVIDER ROLES TABLE (stores permission rules)
CREATE TABLE IF NOT EXISTS public.provider_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(30) UNIQUE NOT NULL,
  label VARCHAR(100) NOT NULL,
  description TEXT,
  permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
  is_system BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Seed default provider roles
INSERT INTO public.provider_roles (role_name, label, description, permissions, is_system) VALUES
('PROVIDER_OWNER', 'Owner', 'Full system access', '["dashboard","organizations","users","billing","crm","monitoring","staff","roles","setup"]'::jsonb, true),
('PROVIDER_ADMIN', 'Admin', 'Manage orgs, users, staff, billing, CRM', '["dashboard","organizations","users","billing","crm","monitoring","staff"]'::jsonb, true),
('PROVIDER_BILLING', 'Billing Manager', 'Billing and payments only', '["dashboard","billing"]'::jsonb, true),
('PROVIDER_SUPPORT', 'Support Agent', 'CRM and support tickets only', '["dashboard","crm"]'::jsonb, true),
('PROVIDER_MONITOR', 'Monitor', 'Read-only dashboard and monitoring', '["dashboard","monitoring"]'::jsonb, true)
ON CONFLICT (role_name) DO UPDATE SET
  label = EXCLUDED.label,
  description = EXCLUDED.description,
  permissions = EXCLUDED.permissions;

-- 4. Seed default provider account (pin: provider123)
INSERT INTO public.provider_users (username, pin, full_name, email, role, is_active) VALUES
('provider', 'provider123', 'System Provider', 'provider@biobridge.com', 'PROVIDER_OWNER', true)
ON CONFLICT (username) DO NOTHING;

-- 5. RLS
ALTER TABLE public.provider_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all on provider_users" ON public.provider_users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on provider_roles" ON public.provider_roles FOR ALL USING (true) WITH CHECK (true);

-- 6. Verify
SELECT 'provider_users' AS tbl, COUNT(*) FROM public.provider_users
UNION ALL SELECT 'provider_roles', COUNT(*) FROM public.provider_roles
UNION ALL SELECT 'organizations', COUNT(*) FROM public.organizations;
