-- ============================================================
-- BioBridge Provider: Payment & Support Tables Migration
-- Run this in Supabase SQL Editor
-- ============================================================

-- 1. PAYMENTS TABLE (Billing/Ledger)
CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  invoice_number VARCHAR(50),
  description TEXT,
  amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'claimed', 'received')),
  payment_method VARCHAR(30) DEFAULT 'bank_transfer',
  payment_date DATE,
  due_date DATE,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_payments_org ON public.payments(organization_id);
CREATE INDEX idx_payments_status ON public.payments(status);

-- 2. SUPPORT TICKETS TABLE (CRM/Complaints)
CREATE TABLE IF NOT EXISTS public.support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  priority VARCHAR(15) NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  category VARCHAR(30) DEFAULT 'general',
  assigned_to VARCHAR(100),
  created_by_name VARCHAR(100),
  created_by_email VARCHAR(200),
  resolution TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_tickets_org ON public.support_tickets(organization_id);
CREATE INDEX idx_tickets_status ON public.support_tickets(status);
CREATE INDEX idx_tickets_priority ON public.support_tickets(priority);

-- 3. RLS POLICIES
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;

-- Allow all operations on payments
CREATE POLICY "Allow all on payments" ON public.payments FOR ALL USING (true) WITH CHECK (true);

-- Allow all operations on support_tickets
CREATE POLICY "Allow all on support_tickets" ON public.support_tickets FOR ALL USING (true) WITH CHECK (true);

-- 4. VERIFY
SELECT 'payments' AS table_name, COUNT(*) AS count FROM public.payments
UNION ALL
SELECT 'support_tickets', COUNT(*) FROM public.support_tickets
UNION ALL
SELECT 'organizations', COUNT(*) FROM public.organizations
UNION ALL
SELECT 'users', COUNT(*) FROM public.users;
