-- ============================================================================
-- COMPREHENSIVE RLS FIX: Add anon policies to ALL public tables
-- Run this in Supabase SQL Editor to fix ALL "permission denied" errors
-- ============================================================================

-- 1. Ensure provider tables exist + seed data
CREATE TABLE IF NOT EXISTS public.provider_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  pin VARCHAR(100) NOT NULL,
  full_name VARCHAR(150),
  email VARCHAR(200),
  role VARCHAR(30) NOT NULL DEFAULT 'PROVIDER_MONITOR'
    CHECK (role IN ('PROVIDER_OWNER','PROVIDER_ADMIN','PROVIDER_BILLING','PROVIDER_SUPPORT','PROVIDER_MONITOR')),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.provider_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(30) UNIQUE NOT NULL,
  label VARCHAR(100) NOT NULL,
  description TEXT,
  permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
  is_system BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.provider_roles (role_name, label, description, permissions, is_system) VALUES
('PROVIDER_OWNER', 'Owner', 'Full system access', '["dashboard","organizations","users","billing","crm","monitoring","staff","roles","setup"]'::jsonb, true),
('PROVIDER_ADMIN', 'Admin', 'Manage orgs, users, staff, billing, CRM', '["dashboard","organizations","users","billing","crm","monitoring","staff"]'::jsonb, true),
('PROVIDER_BILLING', 'Billing Manager', 'Billing and payments only', '["dashboard","billing"]'::jsonb, true),
('PROVIDER_SUPPORT', 'Support Agent', 'CRM and support tickets', '["dashboard","crm"]'::jsonb, true),
('PROVIDER_MONITOR', 'Monitor', 'Read-only dashboard and monitoring', '["dashboard","monitoring"]'::jsonb, true)
ON CONFLICT (role_name) DO UPDATE SET
  label = EXCLUDED.label,
  description = EXCLUDED.description,
  permissions = EXCLUDED.permissions;

INSERT INTO public.provider_users (username, pin, full_name, email, role, is_active) VALUES
('provider', 'provider123', 'System Provider', 'provider@biobridge.com', 'PROVIDER_OWNER', true)
ON CONFLICT (username) DO NOTHING;

-- 2. Enable RLS on all public tables (safe if already enabled)
DO $$
DECLARE
    t TEXT;
BEGIN
    FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public'
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    END LOOP;
END $$;

-- 3. Add anon_read + anon_all policies to EVERY public table
--    This fixes ALL "permission denied" errors for the anon/desktop app key
DO $$
DECLARE
    t TEXT;
BEGIN
    FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public'
    LOOP
        -- DROP old narrow policies that may block anon
        EXECUTE format('DROP POLICY IF EXISTS "authenticated_read" ON public.%I', t);
        EXECUTE format('DROP POLICY IF EXISTS "service_role_all" ON public.%I', t);

        -- SELECT for everyone (anon + authenticated)
        IF NOT EXISTS (
            SELECT 1 FROM pg_policies
            WHERE policyname = 'anon_read' AND tablename = t AND schemaname = 'public'
        ) THEN
            EXECUTE format(
                'CREATE POLICY "anon_read" ON public.%I FOR SELECT USING (true)',
                t
            );
        END IF;

        -- ALL operations for everyone (anon + authenticated)
        IF NOT EXISTS (
            SELECT 1 FROM pg_policies
            WHERE policyname = 'anon_all' AND tablename = t AND schemaname = 'public'
        ) THEN
            EXECUTE format(
                'CREATE POLICY "anon_all" ON public.%I FOR ALL USING (true) WITH CHECK (true)',
                t
            );
        END IF;
    END LOOP;
END $$;

-- 4. Verify
SELECT tablename, COUNT(*) AS policy_count
FROM pg_policies WHERE schemaname = 'public'
GROUP BY tablename ORDER BY tablename;
