-- ============================================================
-- BioBridge Pro HR — MASTER DATABASE SCHEMA
-- Run entire file in Supabase SQL Editor
-- Safe: Uses IF NOT EXISTS / IF NOT EXISTS throughout
-- ============================================================

-- ============================================================
-- STEP 1: ENSURE ORGANIZATIONS TABLE EXISTS FIRST (root table)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    legal_name TEXT,
    registration_number TEXT,
    tax_number TEXT,
    email TEXT,
    phone TEXT,
    website TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT DEFAULT 'Nepal',
    postal_code TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    subscription_plan TEXT DEFAULT 'free' CHECK (subscription_plan IN ('free','starter','professional','enterprise')),
    subscription_expires_at TIMESTAMPTZ,
    max_users INTEGER DEFAULT NULL,
    logo_url TEXT,
    timezone TEXT DEFAULT 'Asia/Kathmandu',
    currency TEXT DEFAULT 'NPR',
    fiscal_year_start TEXT DEFAULT '07-16',
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- STEP 2: CREATE TABLES THAT MAY NOT EXIST YET
-- (Safe: IF NOT EXISTS does nothing if table already exists)
-- ============================================================

-- ── 3.1 USERS ──────────────────────────────────
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    email TEXT,
    full_name TEXT,
    role TEXT DEFAULT 'EMPLOYEE' CHECK (role IN ('SUPER_ADMIN','PROVIDER','ADMIN','MANAGER','SUPERVISOR','EMPLOYEE','OPERATOR','VIEWER')),
    organization_id BIGINT,
    branch_id UUID,
    department_id TEXT,
    designation_id TEXT,
    auth_id UUID,
    employee_id TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    must_change_password BOOLEAN DEFAULT FALSE,
    last_login_at TIMESTAMPTZ,
    failed_login_attempts INTEGER DEFAULT 0,
    locked_until TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.2 BRANCHES ───────────────────────────────
CREATE TABLE IF NOT EXISTS public.branches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    name TEXT NOT NULL,
    code TEXT,
    location TEXT,
    address TEXT,
    phone TEXT,
    email TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.3 DEPARTMENTS ────────────────────────────
CREATE TABLE IF NOT EXISTS public.departments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    name TEXT NOT NULL,
    code TEXT UNIQUE,
    description TEXT,
    parent_id UUID,
    head_id UUID,
    budget NUMERIC DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.4 DESIGNATIONS ───────────────────────────
CREATE TABLE IF NOT EXISTS public.designations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    name TEXT NOT NULL,
    code TEXT UNIQUE,
    level INTEGER DEFAULT 0,
    grade TEXT,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.5 GATES ──────────────────────────────────
CREATE TABLE IF NOT EXISTS public.gates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    branch_id UUID,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.6 DEVICES ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.devices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    brand TEXT DEFAULT 'ZKTeco',
    ip_address TEXT NOT NULL,
    port INTEGER DEFAULT 4370,
    comm_key INTEGER DEFAULT 0,
    machine_number INTEGER DEFAULT 1,
    branch_id UUID,
    gate_id UUID,
    is_default BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'offline',
    subnet_mask TEXT,
    gateway TEXT,
    dns TEXT,
    dhcp BOOLEAN DEFAULT FALSE,
    server_mode TEXT DEFAULT 'Standalone',
    server_address TEXT,
    https_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.7 EMPLOYEES ──────────────────────────────
CREATE TABLE IF NOT EXISTS public.employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    employee_code TEXT UNIQUE NOT NULL,
    first_name TEXT NOT NULL,
    middle_name TEXT,
    last_name TEXT NOT NULL,
    date_of_birth DATE,
    gender TEXT,
    marital_status TEXT,
    nationality TEXT DEFAULT 'Nepali',
    personal_email TEXT,
    personal_phone TEXT,
    current_address TEXT,
    permanent_address TEXT,
    citizenship_number TEXT,
    pan_number TEXT,
    branch_id UUID,
    department_id UUID,
    designation_id UUID,
    employment_type TEXT DEFAULT 'Full-time',
    employment_status TEXT DEFAULT 'Active',
    date_of_joining DATE,
    confirmation_date DATE,
    contract_end_date DATE,
    reporting_manager_id UUID,
    bank_name TEXT,
    account_number TEXT,
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    emergency_contact_relation TEXT,
    photo_url TEXT,
    notes TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.8 ATTENDANCE LOGS ────────────────────────
CREATE TABLE IF NOT EXISTS public.attendance_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id UUID,
    organization_id BIGINT,
    branch_id UUID,
    gate_id UUID,
    device_id UUID,
    timestamp TIMESTAMPTZ NOT NULL,
    log_type TEXT DEFAULT 'in',
    punch_method TEXT DEFAULT 'device',
    is_synced BOOLEAN DEFAULT FALSE,
    synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.9 LEAVE REQUESTS ─────────────────────────
CREATE TABLE IF NOT EXISTS public.leave_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id UUID,
    organization_id BIGINT,
    leave_type TEXT DEFAULT 'Casual Leave',
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'pending',
    approved_by TEXT,
    approved_at TIMESTAMPTZ,
    rejection_reason TEXT,
    applied_by TEXT,
    applied_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.10 PERMISSIONS ──────────────────────────
CREATE TABLE IF NOT EXISTS public.permissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    module TEXT NOT NULL,
    permission TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.11 ROLE PERMISSIONS ─────────────────────
CREATE TABLE IF NOT EXISTS public.role_permissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    role TEXT NOT NULL,
    permission_id UUID,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.12 USER BRANCH ACCESS ───────────────────
CREATE TABLE IF NOT EXISTS public.user_branch_access (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID,
    branch_id UUID,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, branch_id)
);

-- ── 3.13 SALARY STRUCTURES ────────────────────
CREATE TABLE IF NOT EXISTS public.salary_structures (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    employee_id UUID,
    basic_salary NUMERIC DEFAULT 0,
    allowances NUMERIC DEFAULT 0,
    deductions NUMERIC DEFAULT 0,
    effective_from DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.14 PAYROLL RECORDS ──────────────────────
CREATE TABLE IF NOT EXISTS public.payroll_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    employee_id UUID,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    gross_salary NUMERIC DEFAULT 0,
    deductions NUMERIC DEFAULT 0,
    net_pay NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'pending',
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.15 ITEMS ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    item_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    category TEXT DEFAULT 'General',
    quantity INTEGER DEFAULT 0,
    unit_price NUMERIC DEFAULT 0,
    reorder_level INTEGER DEFAULT 10,
    supplier TEXT,
    location TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.16 PROJECTS ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    project_code TEXT UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Planning',
    priority TEXT DEFAULT 'Medium',
    start_date DATE,
    end_date DATE,
    budget NUMERIC DEFAULT 0,
    manager_id UUID,
    client_name TEXT,
    progress INTEGER DEFAULT 0,
    team_size INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.17 TASKS ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID,
    task_name TEXT NOT NULL,
    description TEXT,
    assigned_to UUID,
    status TEXT DEFAULT 'Todo',
    priority TEXT DEFAULT 'Medium',
    due_date DATE,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.18 LEADS ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.leads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    lead_code TEXT UNIQUE,
    name TEXT NOT NULL,
    company TEXT,
    email TEXT,
    phone TEXT,
    status TEXT DEFAULT 'New',
    source TEXT,
    value NUMERIC DEFAULT 0,
    assigned_to UUID,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.19 ASSETS ───────────────────────────────
CREATE TABLE IF NOT EXISTS public.assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    asset_code TEXT UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    category TEXT DEFAULT 'IT Equipment',
    status TEXT DEFAULT 'Available',
    purchase_date DATE,
    purchase_cost NUMERIC DEFAULT 0,
    assigned_to UUID,
    location TEXT,
    warranty_expiry DATE,
    condition TEXT DEFAULT 'Good',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.20 NOTIFICATIONS ────────────────────────
CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sender_id UUID,
    sender_name TEXT,
    receiver_id UUID,
    receiver_type TEXT DEFAULT 'USER',
    branch_id UUID,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    notification_type TEXT DEFAULT 'GENERAL',
    is_read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ
);

-- ── 3.21 INVOICES ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.invoices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    invoice_number TEXT UNIQUE,
    invoice_date DATE,
    due_date DATE,
    contact_name TEXT,
    contact_type TEXT,
    invoice_type TEXT DEFAULT 'sales',
    status TEXT DEFAULT 'draft',
    subtotal NUMERIC DEFAULT 0,
    tax_amount NUMERIC DEFAULT 0,
    discount_amount NUMERIC DEFAULT 0,
    total_amount NUMERIC DEFAULT 0,
    paid_amount NUMERIC DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.22 INVOICE ITEMS ────────────────────────
CREATE TABLE IF NOT EXISTS public.invoice_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id UUID,
    description TEXT NOT NULL,
    quantity NUMERIC DEFAULT 1,
    unit_price NUMERIC DEFAULT 0,
    tax_rate NUMERIC DEFAULT 0,
    discount_rate NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.23 PROVIDER USERS ───────────────────────
CREATE TABLE IF NOT EXISTS public.provider_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    pin VARCHAR(100) NOT NULL,
    full_name VARCHAR(150),
    email VARCHAR(200),
    role VARCHAR(30) NOT NULL DEFAULT 'PROVIDER_MONITOR'
        CHECK (role IN ('PROVIDER_OWNER','PROVIDER_ADMIN','PROVIDER_BILLING','PROVIDER_SUPPORT','PROVIDER_MONITOR')),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.24 PROVIDER ROLES ───────────────────────
CREATE TABLE IF NOT EXISTS public.provider_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(30) UNIQUE NOT NULL,
    label VARCHAR(100) NOT NULL,
    description TEXT,
    permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
    is_system BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.25 PAYMENTS ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    invoice_number VARCHAR(50),
    description TEXT,
    amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','claimed','received')),
    payment_method VARCHAR(30) DEFAULT 'bank_transfer',
    payment_date DATE,
    due_date DATE,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.26 SUPPORT TICKETS ──────────────────────
CREATE TABLE IF NOT EXISTS public.support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    priority VARCHAR(15) NOT NULL DEFAULT 'medium'
        CHECK (priority IN ('low','medium','high','urgent')),
    status VARCHAR(20) NOT NULL DEFAULT 'open'
        CHECK (status IN ('open','in_progress','resolved','closed')),
    category VARCHAR(30) DEFAULT 'general',
    assigned_to VARCHAR(100),
    created_by_name VARCHAR(100),
    created_by_email VARCHAR(200),
    resolution TEXT,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.27 SYSTEM SETTINGS ──────────────────────
CREATE TABLE IF NOT EXISTS public.system_settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    setting_key TEXT NOT NULL,
    setting_value TEXT,
    category TEXT DEFAULT 'general',
    description TEXT,
    setting_type TEXT DEFAULT 'text',
    is_public BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.28 AUDIT LOGS ───────────────────────────
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id BIGINT,
    user_id UUID,
    action TEXT NOT NULL,
    table_name TEXT,
    record_id TEXT,
    old_values JSONB,
    new_values JSONB,
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── 3.29 SYNC QUEUE ───────────────────────────
CREATE TABLE IF NOT EXISTS public.sync_queue (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    table_name TEXT NOT NULL,
    operation TEXT NOT NULL,
    data JSONB NOT NULL,
    supabase_id TEXT,
    priority TEXT DEFAULT 'medium',
    status TEXT DEFAULT 'pending',
    retry_count INTEGER DEFAULT 0,
    error_message TEXT,
    synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- ============================================================
-- STEP 3: ADD MISSING COLUMNS TO ALL TABLES
-- (Safe: table exists after Step 2; ADD COLUMN IF NOT EXISTS is idempotent)
-- ============================================================

ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS max_users INTEGER DEFAULT NULL;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS subscription_expires_at TIMESTAMPTZ;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS subscription_plan TEXT DEFAULT 'free';
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS legal_name TEXT;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS registration_number TEXT;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS tax_number TEXT;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS country TEXT DEFAULT 'Nepal';
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS postal_code TEXT;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS logo_url TEXT;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS timezone TEXT;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS currency TEXT;
ALTER TABLE public.organizations ADD COLUMN IF NOT EXISTS fiscal_year_start TEXT;

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS auth_id UUID;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS employee_id TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN DEFAULT FALSE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMPTZ;

ALTER TABLE public.branches ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE public.branches ADD COLUMN IF NOT EXISTS code TEXT;
ALTER TABLE public.branches ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.branches ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE public.branches ADD COLUMN IF NOT EXISTS email TEXT;

ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS parent_id UUID;
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS head_id UUID;
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS budget NUMERIC DEFAULT 0;

ALTER TABLE public.designations ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE public.designations ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 0;
ALTER TABLE public.designations ADD COLUMN IF NOT EXISTS grade TEXT;

ALTER TABLE public.permissions ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS organization_id BIGINT;

ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS organization_id BIGINT;

ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS applied_by TEXT;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS applied_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public.attendance_logs ADD COLUMN IF NOT EXISTS organization_id BIGINT;

ALTER TABLE public.items ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE public.salary_structures ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE public.payroll_records ADD COLUMN IF NOT EXISTS organization_id BIGINT;

ALTER TABLE public.system_settings ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE public.system_settings ADD COLUMN IF NOT EXISTS setting_type TEXT DEFAULT 'text';
ALTER TABLE public.system_settings ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT TRUE;

ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS organization_id BIGINT;

-- ============================================================
-- STEP 4: SEED DATA (provider roles + default provider user)
-- ============================================================

INSERT INTO public.provider_roles (role_name, label, description, permissions, is_system) VALUES
    ('PROVIDER_OWNER', 'Owner', 'Full system access',
     '["dashboard","organizations","users","billing","crm","monitoring","staff","roles","setup"]'::jsonb, TRUE),
    ('PROVIDER_ADMIN', 'Admin', 'Manage orgs, users, staff, billing, CRM',
     '["dashboard","organizations","users","billing","crm","monitoring","staff"]'::jsonb, TRUE),
    ('PROVIDER_BILLING', 'Billing Manager', 'Billing and payments only',
     '["dashboard","billing"]'::jsonb, TRUE),
    ('PROVIDER_SUPPORT', 'Support Agent', 'CRM and support tickets',
     '["dashboard","crm"]'::jsonb, TRUE),
    ('PROVIDER_MONITOR', 'Monitor', 'Read-only dashboard and monitoring',
     '["dashboard","monitoring"]'::jsonb, TRUE)
ON CONFLICT (role_name) DO UPDATE SET
    label = EXCLUDED.label,
    description = EXCLUDED.description,
    permissions = EXCLUDED.permissions;

INSERT INTO public.provider_users (username, pin, full_name, email, role, is_active) VALUES
    ('provider', 'provider123', 'System Provider', 'provider@biobridge.com', 'PROVIDER_OWNER', TRUE)
ON CONFLICT (username) DO NOTHING;

-- ============================================================
-- STEP 5: CREATE ALL INDEXES (safe — skip if exists)
-- ============================================================

-- organizations
CREATE INDEX IF NOT EXISTS idx_orgs_active ON public.organizations(is_active);

-- users
CREATE INDEX IF NOT EXISTS idx_users_org ON public.users(organization_id);
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users(role);
CREATE INDEX IF NOT EXISTS idx_users_active ON public.users(is_active);
CREATE INDEX IF NOT EXISTS idx_users_auth ON public.users(auth_id);

-- branches
CREATE INDEX IF NOT EXISTS idx_branches_org ON public.branches(organization_id);

-- departments
CREATE INDEX IF NOT EXISTS idx_dept_org ON public.departments(organization_id);

-- designations
CREATE INDEX IF NOT EXISTS idx_design_org ON public.designations(organization_id);

-- employees
CREATE INDEX IF NOT EXISTS idx_emp_code ON public.employees(employee_code);
CREATE INDEX IF NOT EXISTS idx_emp_org ON public.employees(organization_id);
CREATE INDEX IF NOT EXISTS idx_emp_branch ON public.employees(branch_id);
CREATE INDEX IF NOT EXISTS idx_emp_status ON public.employees(employment_status);

-- leave_requests
CREATE INDEX IF NOT EXISTS idx_leave_emp ON public.leave_requests(employee_id);
CREATE INDEX IF NOT EXISTS idx_leave_org ON public.leave_requests(organization_id);

-- attendance_logs
CREATE INDEX IF NOT EXISTS idx_att_emp_time ON public.attendance_logs(employee_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_att_org ON public.attendance_logs(organization_id);

-- salary_structures
CREATE INDEX IF NOT EXISTS idx_salary_org ON public.salary_structures(organization_id);
CREATE INDEX IF NOT EXISTS idx_salary_emp ON public.salary_structures(employee_id);

-- payments
CREATE INDEX IF NOT EXISTS idx_payments_org ON public.payments(organization_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON public.payments(status);

-- support_tickets
CREATE INDEX IF NOT EXISTS idx_tickets_org ON public.support_tickets(organization_id);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON public.support_tickets(status);
CREATE INDEX IF NOT EXISTS idx_tickets_priority ON public.support_tickets(priority);

-- system_settings
CREATE INDEX IF NOT EXISTS idx_settings_org ON public.system_settings(organization_id);

-- audit_logs
CREATE INDEX IF NOT EXISTS idx_audit_org ON public.audit_logs(organization_id);
CREATE INDEX IF NOT EXISTS idx_audit_user ON public.audit_logs(user_id);

-- sync_queue
CREATE INDEX IF NOT EXISTS idx_sync_pending ON public.sync_queue(status) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_sync_table ON public.sync_queue(table_name);

-- ============================================================
-- STEP 6: UPDATE TRIGGER (auto-update updated_at)
-- ============================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
    t TEXT;
BEGIN
    FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public'
    LOOP
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = t AND column_name = 'updated_at'
        ) THEN
            IF NOT EXISTS (
                SELECT 1 FROM pg_trigger
                WHERE tgname = 'set_updated_at' AND tgrelid = (format('public.%I', t))::regclass
            ) THEN
                EXECUTE format(
                    'CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column()',
                    t
                );
            END IF;
        END IF;
    END LOOP;
END $$;

-- ============================================================
-- STEP 7: ROW LEVEL SECURITY (RLS)
-- ============================================================

DO $$
DECLARE
    t TEXT;
BEGIN
    FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public'
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    END LOOP;
END $$;

DO $$
DECLARE
    t TEXT;
BEGIN
    FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public'
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_policies
            WHERE policyname = 'authenticated_read' AND tablename = t AND schemaname = 'public'
        ) THEN
            EXECUTE format(
                'CREATE POLICY "authenticated_read" ON public.%I FOR SELECT TO authenticated USING (true)',
                t
            );
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM pg_policies
            WHERE policyname = 'service_role_all' AND tablename = t AND schemaname = 'public'
        ) THEN
            EXECUTE format(
                'CREATE POLICY "service_role_all" ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)',
                t
            );
        END IF;
    END LOOP;
END $$;

-- ============================================================
-- STEP 8: REALTIME (live sync)
-- ============================================================

DO $$
DECLARE
    t TEXT;
BEGIN
    FOR t IN
        SELECT unnest(ARRAY[
            'employees','attendance_logs','leave_requests','items','projects',
            'leads','assets','notifications','branches','gates','devices',
            'users','organizations','payments','support_tickets'
        ])
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_publication_tables
            WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = t
        ) THEN
            EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
        END IF;
    END LOOP;
END $$;

-- ============================================================
-- DONE. Run the commented queries below to verify:
-- ============================================================

-- Check all table row counts:
-- SELECT 'organizations' AS tbl, COUNT(*) FROM public.organizations
-- UNION ALL SELECT 'users', COUNT(*) FROM public.users
-- UNION ALL SELECT 'provider_users', COUNT(*) FROM public.provider_users
-- UNION ALL SELECT 'provider_roles', COUNT(*) FROM public.provider_roles
-- UNION ALL SELECT 'payments', COUNT(*) FROM public.payments
-- UNION ALL SELECT 'support_tickets', COUNT(*) FROM public.support_tickets
-- UNION ALL SELECT 'branches', COUNT(*) FROM public.branches
-- UNION ALL SELECT 'departments', COUNT(*) FROM public.departments
-- UNION ALL SELECT 'designations', COUNT(*) FROM public.designations
-- UNION ALL SELECT 'employees', COUNT(*) FROM public.employees
-- UNION ALL SELECT 'permissions', COUNT(*) FROM public.permissions
-- UNION ALL SELECT 'attendance_logs', COUNT(*) FROM public.attendance_logs
-- UNION ALL SELECT 'leave_requests', COUNT(*) FROM public.leave_requests
-- UNION ALL SELECT 'system_settings', COUNT(*) FROM public.system_settings
-- ORDER BY tbl;

-- Check organization_id column exists on all key tables:
-- SELECT column_name, table_name FROM information_schema.columns
-- WHERE table_schema = 'public' AND column_name = 'organization_id'
-- ORDER BY table_name;

-- ============================================================
-- STATUS SUMMARY
-- ============================================================
-- ✅ INCLUDED:
--   organizations (max_users, subscription_plan, deleted_at, soft delete)
--   users (auth_id FK→auth.users, organization_id, role CHECK with PROVIDER)
--   branches, gates, devices (organization_id)
--   departments, designations (organization_id, hierarchy)
--   employees (organization_id, full_name, employment_status)
--   attendance_logs, leave_requests (organization_id)
--   permissions, role_permissions (organization_id)
--   items, projects, tasks, leads, assets (organization_id)
--   salary_structures, payroll_records (organization_id)
--   invoices, invoice_items (organization_id)
--   notifications (receiver_type)
--   system_settings (organization_id, key-value)
--   audit_logs, sync_queue (JSONB, offline-first)
--   provider_users + provider_roles (seed data: provider/provider123)
--   payments + support_tickets (provider billing + CRM)
--   update_updated_at trigger on all tables
--   RLS policies on all tables (authenticated_read + service_role_all)
--   Realtime on all live tables
--
-- 🔲 PENDING (future):
--   leave_types, leave_balances, attendance_daily
--   employee_documents, employee_history, salary_components
--   shifts, holidays, overtime_records
--   chart_of_accounts, journal_entries (finance)
--   warehouses, stock, purchase_orders (inventory)
--   timesheets, documents, loans
-- ============================================================
